name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    # pull_request:
    pull_request_target:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  IS_TAG: ${{ github.ref_type == 'tag'}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
          
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}

      - name: Print Branch
        run: echo ${{env.BRANCH_NAME}}

      - name: Pick Nexus Repo ID
        id: nexusRepoID
        if: env.IS_TAG == 'true' && github.repository_owner == 'ikmdev'
        run: |
          echo "NEXUS_RELEASE_ID=maven-releases" >> $GITHUB_OUTPUT

      - name: Print Action
        run: echo ${{github.event_name}}
      
      - name: Deploy Artifacts To Nexus
        if: github.repository_owner == 'ikmdev' && github.event_name != 'pull_request'
        uses: ikmdev/maven-nexus-deploy-action@main
        with:
          nexus_repo_id: ${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || 'maven-snapshots'}}
          nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
  
  