name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  IS_TAG: ${{ github.ref_type == 'tag'}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - name: tag test
        if: env.IS_TAG
        run: echo "tag test"

      - name: test
        run: echo "test"
        
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
          
      - name: Build IKMDEV Code
        if: github.event.repository.name != 'github_actions_test'
        uses: ikmdev/maven-clean-install-build-action@v1.1.0
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
          sonarcloud_tests: ${{ 'src/test/java' }}
