name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  IS_TAG: ${{ github.ref_type == 'tag'}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - name: Pull Request Version Validation
        if: github.event_name == 'pull_request'
        uses: ikmdev/maven-pull-request-version-validation-action@main
        
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
          
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@testing-build
        with:
          branch_name: ${{env.BRANCH_NAME}}
         
